feat: profile_info
today-they-learned/ttl_front pull request #10
Opened 2022-01-30 08:35 UTC by soyekwon

## 작업 내용
- 마이페이지 사용자 정보 나타내주는 페이지

## 참고 사항
- 

## 기타 사항
- 일단 사용자 프로필 정보를 initialInfo에 담아서 작업했습니다. 
- full사이즈로 작업하라 해서  상대적 크기 단위인 rem을 사용했는데 rem단위로 하는거 맞나염 .. ?

2022-01-30 09:59 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +};
p1: initialInfo.tags.join(" ")으로 간단하게 처리될 것 같아요

2022-01-30 10:18 UTC, soyekwon commented on src/components/mypage/ProfileInfo.js
> +};
댑악

2022-01-31 12:14 UTC, minjj0905 requested changes
화이팅 😊

2022-01-31 12:14 UTC, minjj0905 commented on src/components/mypage/ProfileInfo.js
> +
p2: styled components 는 따로따로 분리해서 개별로 작성하고, 각 태그에 classname을 쓰는 것 대신 생성한 styled components를 이용하면 됩니다..! (지금 방식은 makeStyles 같은 다른 방식에 어울리는 방식..)

2022-01-31 12:14 UTC, minjj0905 commented on src/components/mypage/ProfileInfo.js
> +};
아니면 return 부분에 map을 이용해서 데이터를 뿌려줄 수도 있을것같아요오

2022-01-31 12:14 UTC, minjj0905 commented on src/App.js
> +        <Route exact path="/mypage_edit" component={MypageEdit} />
hmm,, 여기 이렇게 page, page edit 두 개 페이지 별도로 작성하는 거 밖에 방법이 없을까요.. 뭔가 맘에 쏙 드는 방법은 아닌데 해결책 아시는 분..? 안쪽 컴포넌트만 건드려서는 못 바꾸려나... @shinkeonkim

2022-01-31 12:14 UTC, minjj0905 commented on src/components/mypage/ProfileInfo.js
> +
p2: 이미지는 public/images 아래로 모읍시당

2022-01-31 12:14 UTC, minjj0905 commented on package.json
> +    "react-router-dom": "^5.3.0",
유찬님이 6버전으로 올려서 컨플릭트 나면 6으로 맞춰주세요~

2022-01-31 12:14 UTC, minjj0905 commented on .eslintrc.js
> +    'import/no-unresolved': 'off',
아마 제거랑 컨플릭트 나면 다 적용되도록 수정 부탁드림다

2022-02-02 11:40 UTC, cychann commented on src/App.js
> +        <Route exact path="/mypage_edit" component={MypageEdit} />
음 mypage 컴포넌트에  page, page edit 라는 2개의 하위 컴포넌트를 만들고, 
page edit에서 편집한 프로필 정보를 mypage로 넘기고 page에 뿌려주고 이렇게 mypage라는 하나의 상위 컴포넌트에서  프로필에 대한 정보를 제어하는 방식으로 하면 안되려나욤..?

2022-02-04 06:10 UTC, minjj0905 commented on src/App.js
> +        <Route exact path="/mypage_edit" component={MypageEdit} />
어차피 page edit에서 완료누르면 그걸 서버에 보내고 mypage에서는 다시 api 호출하는거라...
그냥 두개로 둡시다 ... 티안나면 갠찮을겁니당

2022-02-04 06:11 UTC, minjj0905 commented
린트 설정 컨플릭트는 제가 수정했어여

2022-02-04 09:22 UTC, shinkeonkim commented on src/App.js
> +        <Route exact path="/mypage_edit" component={MypageEdit} />
state로 edit임으로 표현해서 하면 될 것 같은데...

근데, 개인적으로 전 route가 너무 마음에 안듭니다.

- /me
- /me/edit

이 더 깔끔해보여요

2022-02-04 09:24 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +};
initialInfo는 중요한 초기 변수이기에, 문자열이나 기타 정보를 다 비워두고, 

다른 곳에서 dummyInitialInfo를 만들어서 Object.assign(IntialInfo, dummyInitialInfo); 식으로 하는게 이후에도 더 좋을 것 같아요

2022-02-04 09:24 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +
route로 처리해주세요

2022-02-04 09:25 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +        <ul className="tag">{tagList()}</ul>
p1: 왜 ul 인가요? ul로 감싸고 li로 넣거나, 그냥 span이면 될 것 같습니다

2022-02-04 09:26 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +
이거 해주시면 될 것 같습니다. 지금 방식은 makeStyles ㅇㅇ..

2022-02-04 09:27 UTC, shinkeonkim commented on src/pages/Mypage/Mypage.jsx
> +  // const [info, setInfo] = useState(initialInfo);
p1: 이거 주석처리 할 필요 없이 여기에서  ProfileInfo에 info 넣어주는 코드 넣어주세요

2022-02-04 09:29 UTC, shinkeonkim commented on src/pages/Mypage/Mypage.jsx
> +const Mypage = () => {
p2: MyPage가 아니라 ProfilePage로 한다음에, 본인 페이지/다른 사람 페이지 를 구별하는 state를 하나 둬서 하는게 좋아 보입니다. 어차피 같은 구성의 페이지인데 따로 둘 필요가 없어 보여요.

2022-02-04 10:28 UTC, shinkeonkim commented
이 PR과 https://github.com/today-they-learned/ttl_front/pull/11 PR이 겹쳐서, 이 PR은 close 할게요.

2022-02-04 10:29 UTC, closed without merging