Mypage edit/6
today-they-learned/ttl_front pull request #11
Opened 2022-01-30 08:42 UTC by soyekwon

## 작업 내용
- 프로필 편집 페이지 구성 

## 기타 사항
- 사용자의 정보를 담고 있는 initialInfo를 props로 주고받아야 할거같아서 App.js에 initialInfo선언하고 각 페이지에 props로 넘겨줬는데 음 ... 음 .... 뭔가 잘못하고있는 느낌 ...

2022-01-31 12:21 UTC, minjj0905 requested changes
앞전 pr에 있는 내용이랑 같이 진행해주십쇼 😇

2022-01-31 12:21 UTC, minjj0905 commented on src/App.js
> +  };
p1: 더미데이터는 별도 파일로 생성해서 테스트하면 좋을것같고,,, app에서 데이터 불러와서 처리하지 않도록 .... 각 페이지 내에서 해결 봅시다용. 나중에 api로 불러오게 될 거니까용

2022-01-31 12:21 UTC, minjj0905 commented on src/components/mypage/ProfileInfo.js
> +        <Button className="editButton" onClick={handleClick}>
p5: 따로 함수 빼지말고 그냥 화살표함수로 써도 괜찮을듯..? 그리구 Link to 이용하는건 어떠신가여 .. 뭐 .. 쓰는건자유..

2022-01-31 12:21 UTC, minjj0905 commented on src/pages/Mypage/MypageEdit.jsx
> +  background-color: white;
global styles 에 f8f8f8 로 했으니까 여긴 빼두 댈듯...

2022-02-04 07:07 UTC, soyekwon commented on src/App.js
> +  };
mypage에서 데이터를 불러오도록 바꿨습니당

2022-02-04 07:08 UTC, soyekwon commented on src/pages/Mypage/MypageEdit.jsx
> +  background-color: white;
바꿨습니다유

2022-02-04 09:40 UTC, shinkeonkim requested changes

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileEdit.js
> +  };
이거 민정이 브랜치에 있는 useInput 쓰면 좋을 것 같아요

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileEditStyled.js
> +export const InfoEdit = styled.div`
여기도 마찬가지로 styled component는 styled component 답게 활용해주세요

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileEditStyled.js
> +    margin-bottom: 1.2rem;
p1: `margin: 0.5rem auto 1.2rem 1.5rem;`

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +/* eslint-disable react/prop-types */
q: 뭐가 왜 이렇게 많죠?

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileInfo.js
> +          onClick={() => setTab(!tab)}
`onClick={() => setTab(!tab)}` 대신에 `onClick={setTab(!tab)}` 으로는 안되나요?

2022-02-04 09:40 UTC, shinkeonkim commented on src/pages/Mypage/Mypage.jsx
> +    </MyPage>
아하 여기에서는 state로 관리되네요?

2022-02-04 09:40 UTC, shinkeonkim commented on src/pages/Mypage/Mypage.jsx
> +      edit_mode: !info.edit_mode,
p1: 안전하게 !로 하지 않고, false 로 가는게 좋을 것 같아요

2022-02-04 09:40 UTC, shinkeonkim commented on src/pages/Mypage/Mypage.jsx
> +
이전 pr과 많은 차이가 있군요 음

2022-02-04 09:40 UTC, shinkeonkim commented on src/components/mypage/ProfileEditStyled.js
> +  }
p5: 공통적으로 나오는 style들이 많이 있는 것 같아요. 조금 간단하게 묶을 방법이 있는지 한번 생각해볼 수 있을 것 같은데, 도전?

2022-02-04 11:49 UTC, minjj0905 commented on src/components/mypage/ProfileEdit.js
> +
import * as Styled  from ~~~

이렇게 import하면 한줄로 가능하구 나중에 쓸때는
<Styled.InfoEdit>
이렇게 쓸 수 있습니당

2022-02-04 11:49 UTC, minjj0905 commented on src/components/mypage/ProfileInfoStyled.js
> +`;
여기도 마찬가지로.. styled components 사용할때는 클래스네임 설정하지 않고 각각 태그 만드는걸로!

2022-02-04 11:49 UTC, minjj0905 commented on src/pages/Mypage/Mypage.jsx
> +`;
백그라운드컬러 설정안해도돼요~

2022-02-04 11:49 UTC, minjj0905 commented on src/components/mypage/ProfileEdit.js
> +    console.log(info.username);
pr 올릴땐 console log 는 삭제하기!

2022-02-04 11:49 UTC, minjj0905 commented on src/components/mypage/ProfileEdit.js
> +          </Button>
프로필 수정페이지에서는 취소 / 수정 두가지 버튼이 있어야 할 것 같아용
수정했다가 하기 싫으면 다시 원래대로 돌려줘야하니까...

참고자료 solved.ac
![image](https://user-images.githubusercontent.com/55120738/152496303-256f66b9-a282-4a78-ba02-a7db0f3d78b3.png)

2022-02-04 11:49 UTC, minjj0905 commented on src/pages/Mypage/Mypage.jsx
> +  tags: ['#algorithm', '#python', '#react'],
데이터는 그냥 문자열로 올거라서, 태그 표시할때는 🏷️ 이런 이모지 있는데 (유찬님이 사이드바에 쓴거) 이거로 앞에 표시하면 좋겠슴당

2022-02-04 11:49 UTC, minjj0905 commented on src/pages/Mypage/Mypage.jsx
> +};
p1: edit mode 를 state로 토글할거라면, 유저 info안에 있는게 아니라 mypage의 state로 따로 관리되어야겠죠?

2022-02-04 11:49 UTC, minjj0905 commented on src/pages/Mypage/Mypage.jsx
> +  };
위에 썼듯이 editmode가 state라면 그냥
```javascript
const [editMode, setEditMode] = useState(false);
```
이렇게 해놓고
나중에 사용할때는 `setEditMode(!editMode)` 이렇게 하면 토글되게... 하면 될듯

2022-02-04 12:30 UTC, merged