userpage
today-they-learned/ttl_front pull request #84
Opened 2022-02-19 10:11 UTC by soyekwon

## 작업 내용
- Mypage -> Userpage로 수정
- 다른 유저 페이지 접속했을 땐 팔로우버튼, 내 프로필 접속했을 땐 프로필 편집 버튼 

## 그런데 !!!! 
- 다른 유저페이지에서 바로 내 프로필 누를 때만 새로고침을 해야 내 프로필 화면으로 바뀜 
    -> /userpage/:id -> :id 값만 바뀔 때 -> 이건 계속 해결해보겠슴다

2022-02-19 12:56 UTC, minjj0905 commented
잠시만요 프리뷰 기능 이제 켤게요 다들 확인해보자요

2022-02-19 12:59 UTC, minjj0905 commented
프리뷰..안켜지네.. pr에 사진 추가해주세영

2022-02-19 17:31 UTC, cychann commented on src/components/Mypage/ProfileInfo.jsx
> +  const { id } = useParams();
이 컴포넌트의 props로 id 전달해줬는데 굳이 선언안하고 props로 받아서 써도 되지 않을까욤

2022-02-20 08:54 UTC, minjj0905 requested changes

2022-02-20 08:54 UTC, minjj0905 commented on .eslintrc.js
> +    'import/no-unresolved': ['error', { caseSensitive: false }],
p1: 이 에러 rule 좀 켜볼까요 이건 사실 키고하는게 맞는 룰이라 ...

2022-02-20 08:54 UTC, minjj0905 commented on src/pages/Article/Article.jsx
> +              </button>
p2: 여긴 이렇게 연결하는거보다 다른 방식이 좋을거같아서 .. 다른 파트에서 userpage로 연결하는 부분은 제가 짤게요 빼주시면 좋을듯

2022-02-20 08:54 UTC, minjj0905 commented on src/components/Mypage/ProfileInfo.jsx
> +        {tab ? <CalendarHeatMap id={id} /> : <TIL id={info.id} />}
p1: til에 들어가는 아이디랑 앞에 calendarHeatmap 아이디랑 맞춰주세요~ useParams 이용할 이유가 없으니 props로 오는 것으로 통일

2022-02-20 08:54 UTC, minjj0905 commented on src/components/Mypage/ProfileInfo.jsx
> +  const { id } = useParams();
p1: 위 의견 받습니다 22

2022-02-20 10:54 UTC, shinkeonkim commented on src/App.js
> +            <Route path="/userpage/:id" element={<Userpage />} />
route에서는 /user 가 더 매끄러운 것 같아요

2022-02-20 10:56 UTC, shinkeonkim requested changes

2022-02-20 10:56 UTC, shinkeonkim commented on src/components/Mypage/ProfileInfo.jsx
> +  const { id } = useParams();
선택지에 따라 다를 것 같네요. 음 props를 믿느냐, route를 믿느냐인데.. 코드가 깔끔해지는 쪽으로 가시면 될 것 같습니다

2022-02-20 10:56 UTC, shinkeonkim commented on src/pages/Article/Article.jsx
> +              </button>
저도 이것보다는 그냥 Link 쓰는게 더 좋아보이네여

2022-02-22 16:12 UTC, minjj0905 commented
Duplicate of #90

2022-02-22 16:12 UTC, closed without merging