Feed configuration
today-they-learned/ttl_front pull request #9
Opened 2022-01-30 03:56 UTC by cychann

## 작업 내용
- 해당 브랜치/PR에서 작업한 내용을 모두 나열합니다.
- 최대한 리뷰어를 배려하여 작성하도록 합니다.

## 참고 사항
- 참고한 내용을 첨부합니다.

## 기타 사항
- 코드를 작성하면서 고민되었던 부분을 작성합니다.
- 리뷰어가 참고할 내용 또는 기타 사항을 작성합니다.
- 배포/마이그레이션 등을 수행할 때 주의해야하는 사항을 작성합니다.

2022-01-30 07:16 UTC, shinkeonkim requested changes

2022-01-30 07:16 UTC, shinkeonkim commented on src/components/post_card/post_card.jsx
> +        <div style={{ display: 'flex', alignItems: 'center' }}>
p5: 요런 스타일은 따로 만들어놔도 되지 않을까 싶네요
align-center-container?

2022-01-30 07:16 UTC, shinkeonkim commented on src/components/post_card/post_card.jsx
> +`;
p1: 주석처리된건 지워주세요

2022-01-30 07:16 UTC, shinkeonkim commented on src/components/post_card/post_card.jsx
> +  line-height: 1rem;
아 뭔가..너무 긴데... styled-component를 쓰면 어쩔 수 없는걸까요..
더 깔끔한 방법은 없을까요?

2022-01-30 07:16 UTC, shinkeonkim commented on src/layouts/desktop.layout.js
> +  };
p1: 왜 이걸 라우트로 제어하지 않나요? Main, Group, Follow 페이지 컴포넌트를 DesktopLayout으로 감싸고 라우트에서 해당 페이지로 향하게 하면 되지 않나요? 굳이 locationPath로 routing을 구현하신 이유가 있나요?

2022-01-30 07:16 UTC, shinkeonkim commented on src/pages/follow/follow.jsx
> +      thumbnail: 'images/thumbnail.png',
더미 데이터는 별도 파일을 만들고 테스트해주시면 더 좋을 것 같습니다

2022-01-30 07:16 UTC, shinkeonkim commented on src/pages/follow/follow.jsx
> +          <p style={{ fontFamily: 'GS-B', fontSize: '2rem', color: '#707bf3' }}>
기본적인 fontFamily나 color에 대한 styled-component들을 한번 잡고 가야겠네요..

2022-01-30 07:16 UTC, shinkeonkim commented on src/pages/group/group.jsx
> +        '치즈덕 명언 키야이제부터라도 열심히 자바스크립트 공부를 해야겠다는 생각이 드는 사진이다. 빠빠샤!자료(data) : 프로그래밍에서 프로그램이 처리할 수 있는 모든 것자료형(data type) : 자료 형태에 따라 나눠 놓은 것 1. 문자열 자료형 2. 숫자 자료형 ',
p2: 여기도 마찬가지로 더미 데이터를 별도 파일에 만들어주시면 좋을 것 같습니다.

2022-01-30 10:29 UTC, minjj0905 commented on src/App.js
> +            <Route path="/main" element={<Main />} />
<Route exact path="/main" element={<Main />} />

2022-01-31 11:53 UTC, cychann commented on src/layouts/desktop.layout.js
> +  };
혹시 말씀해주신게 해당 컴포넌트에서
const DesktopLayout = () => {
  return (
    <Routes>
      <Route path="/" element={<Main />} />
      <Route path="/group" element={<Group />} />
      <Route path="/follow" element={<Follow />} />
    </Routes>
  );
};

export default DesktopLayout;

이런식으로 라우트를 사용하는 것을 의도하시는게 맞을까요?

2022-01-31 12:07 UTC, minjj0905 commented
그.. 저기 .. 저도 리뷰어좀.. 추가...... (머쓱

2022-02-02 05:36 UTC, cychann commented on src/components/post_card/post_card.jsx
> +        <div style={{ display: 'flex', alignItems: 'center' }}>
네넵 추후에 따로 만들어놓고 사용하기로 했습니다!

2022-02-02 05:36 UTC, cychann commented on src/components/post_card/post_card.jsx
> +`;
알겠습니다 :)

2022-02-02 05:37 UTC, cychann commented on src/components/post_card/post_card.jsx
> +  line-height: 1rem;
이렇게 styled-component가 길어지는 경우에만 해당폴더에 styled 부분만 파일로 따로 빼서 import해서 가져오는 식으로 고쳐보겠습니다

2022-02-02 05:39 UTC, cychann commented on src/layouts/desktop.layout.js
> +  };
이제 각각 메뉴로 url을 연결하는 것이 아니라, 게시글을 보여주는 컴포넌트를 하나로 통일 시키고 해당 컴포넌트에서 어떤 메뉴가 클릭되었는지를 처리하는 방식으로 고칠 예정입니다!

2022-02-02 05:39 UTC, cychann commented on src/pages/follow/follow.jsx
> +      thumbnail: 'images/thumbnail.png',
네넵 알겠습니다 :)

2022-02-02 11:30 UTC, shinkeonkim approved these changes

2022-02-04 06:08 UTC, minjj0905 approved these changes
LGTM 👍

2022-02-04 11:30 UTC, merged